[theme]
# Setze die prim채re Akzentfarbe (z.B. f체r Buttons)
primaryColor = "#0058aaff" 

# Hintergrundfarbe der gesamten App
backgroundColor = "#131313ff" 

# Hintergrundfarbe der Seitenleiste/Widgets
secondaryBackgroundColor = "#000000ff" 

# Standardtextfarbe
textColor = "#ffffffff" 

# Schriftart
font = "sans serif" # Optionen: "sans serif", "serif", "monospace"

# Zus채tzliche Einstellungen...
base = "dark" # Oder "dark" f체r den Streamlit Dark Mode

[server]
headless = true

